params:
  Robot:
    qpos:
      {
        "panda_joint1": 0.5071,
        "panda_joint2": -0.5104,
        "panda_joint3": -0.4926,
        "panda_joint4": -2.5945,
        "panda_joint5": -0.2663,
        "panda_joint6": 2.1293,
        "panda_joint7": 0.88,
        "panda_finger_joint.*": 0.04,
      }
  DeformableObject:
    object:
      #path: "source/assets/Tube/tube/usd/tube.usd"
      path: "source/assets/Plush/usd/rabbit/usd/rabbit_deform.usd"

      simulation_hexahedral_resolution: 16
      vertex_velocity_damping: 0.0
      scale: [0.6, 0.6, 0.6] #[0.03, 0.03, 0.03]
      pos: [0.50, -0.0, 0.025]
      rot:
        axis: [1, 2, 0]
        angles: [-1.57, 1.57, -1.57]
      random_parmas: False
      params:
        dynamic_friction: [0.10, 1.0]
        youngs_modulus: [3000000, 3000000000]
        poissons_ratio: [0.1, 0.50]
        elasticity_damping: [0.00, 20]
        damping_scale: [0.1, 1.0]
        simulation_hexahedral_resolution: [2, 64]
        mass: [0.1, 1000]
      attach_robot:
        init: False
        attach_object_path: "/World/envs/env_.*/Robot/panda_hand"
        attach_offset: [0, 0, -0.33]
        attact_yet: False

    # deform_object1:
    #   path: "source/assets/Plush/usd/cat/usd/cat_deform.usd"
    #   simulation_hexahedral_resolution: 32
    #   vertex_velocity_damping: 0.0
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [1.0, -0.0, 0.5]
    #   rot:
    #     axis: [1]
    #     angles: [0]
    #   params:
    #     dynamic_friction: [0.10, 1.0]
    #     youngs_modulus: [30000000, 300000000]
    #     poissons_ratio: [0.1, 0.50]
    #     elasticity_damping: [0.00, 0.2]
    #     damping_scale: [0.1, 1.0]
    #     simulation_hexahedral_resolution: [2, 64]
    #     mass: [0.1, 1000]

    # deform_object2:
    #   path: "source/assets/Plush/usd/cat/usd/cat_deform.usd"
    #   simulation_hexahedral_resolution: 32
    #   vertex_velocity_damping: 0.0
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [1.0, 0.8, 0.5]
    #   rot:
    #     axis: [1]
    #     angles: [0]
    #   params:
    #     dynamic_friction: [0.10, 1.0]
    #     youngs_modulus: [3000000, 30000000]
    #     poissons_ratio: [0.1, 0.50]
    #     elasticity_damping: [0.00, 0.2]
    #     damping_scale: [0.1, 1.0]
    #     simulation_hexahedral_resolution: [2, 64]
    #     mass: [0.1, 1000]

    # deform_object3:
    #   path: "source/assets/Plush/usd/cat/usd/cat_deform.usd"
    #   simulation_hexahedral_resolution: 32
    #   vertex_velocity_damping: 0.0
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.0, -0.8, 0.5]
    #   rot:
    #     axis: [1]
    #     angles: [0]
    #   params:
    #     dynamic_friction: [0.10, 1.0]
    #     youngs_modulus: [300000, 3000000]
    #     poissons_ratio: [0.1, 0.50]
    #     elasticity_damping: [0.00, 0.2]
    #     damping_scale: [0.1, 1.0]
    #     simulation_hexahedral_resolution: [2, 64]
    #     mass: [0.1, 1000]

    # deform_object4:
    #   path: "source/assets/Plush/usd/cat/usd/cat_deform.usd"
    #   simulation_hexahedral_resolution: 32
    #   vertex_velocity_damping: 0.0
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.0, -0.0, 0.5]
    #   rot:
    #     axis: [1]
    #     angles: [0]
    #   params:
    #     dynamic_friction: [0.10, 1.0]
    #     youngs_modulus: [30000, 300000]
    #     poissons_ratio: [0.1, 0.50]
    #     elasticity_damping: [0.00, 0.2]
    #     damping_scale: [0.1, 1.0]
    #     simulation_hexahedral_resolution: [2, 64]
    #     mass: [0.1, 1000]

    # deform_object5:
    #   path: "source/assets/Plush/usd/cat/usd/cat_deform.usd"
    #   simulation_hexahedral_resolution: 32
    #   vertex_velocity_damping: 0.0
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.0, 0.8, 0.5]
    #   rot:
    #     axis: [1]
    #     angles: [0]
    #   params:
    #     dynamic_friction: [0.10, 1.0]
    #     youngs_modulus: [3000, 30000]
    #     poissons_ratio: [0.1, 0.50]
    #     elasticity_damping: [0.00, 0.2]
    #     damping_scale: [0.1, 1.0]
    #     simulation_hexahedral_resolution: [2, 64]
    #     mass: [0.1, 1000]

    # deform_object6:
    #   path: "source/assets/Plush/usd/cat/usd/cat_deform.usd"
    #   simulation_hexahedral_resolution: 32
    #   vertex_velocity_damping: 0.0
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [3.0, -0.8, 0.5]
    #   rot:
    #     axis: [1]
    #     angles: [0]
    #   params:
    #     dynamic_friction: [0.10, 1.0]
    #     youngs_modulus: [300, 3000]
    #     poissons_ratio: [0.1, 0.50]
    #     elasticity_damping: [0.00, 0.2]
    #     damping_scale: [0.1, 1.0]
    #     simulation_hexahedral_resolution: [2, 64]
    #     mass: [0.1, 1000]

    # deform_object7:
    #   path: "source/assets/Plush/usd/cat/usd/cat_deform.usd"
    #   simulation_hexahedral_resolution: 32
    #   vertex_velocity_damping: 0.0
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [3.0, -0.0, 0.5]
    #   rot:
    #     axis: [1]
    #     angles: [0]
    #   params:
    #     dynamic_friction: [0.10, 1.0]
    #     youngs_modulus: [30, 300]
    #     poissons_ratio: [0.1, 0.50]
    #     elasticity_damping: [0.00, 0.2]
    #     damping_scale: [0.1, 1.0]
    #     simulation_hexahedral_resolution: [2, 64]
    #     mass: [0.1, 1000]

    # deform_object8:
    #   path: "source/assets/Plush/usd/cat/usd/cat_deform.usd"
    #   simulation_hexahedral_resolution: 32
    #   vertex_velocity_damping: 0.0
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [3.0, 0.8, 0.5]
    #   rot:
    #     axis: [1]
    #     angles: [0]
    #   params:
    #     dynamic_friction: [0.10, 1.0]
    #     youngs_modulus: [30, 300]
    #     poissons_ratio: [0.1, 0.50]
    #     elasticity_damping: [0.00, 0.2]
    #     damping_scale: [0.1, 1.0]
    #     simulation_hexahedral_resolution: [2, 64]
    #     mass: [0.1, 1000]

  RigidObject:
    # rigid_object:
    #   path: "source/assets/Plush/usd/rabbit/usd/cube_rigid.usd"
    #   simulation_hexahedral_resolution: 8
    #   vertex_velocity_damping: 0.0
    #   scale: [0.05, 0.05, 0.05] #[0.03, 0.03, 0.03]
    #   pos: [0.60, -0.0, 0.04]
    #   rot:
    #     axis: [1, 2, 0]
    #     angles: [-1.57, 1.57, -1.57]

    # rigid_object1:
    #   path: "source/assets/Plush/usd/rabbit/usd/rabbit_rigid.usd"
    #   scale: [2.0, 2.0, 2.0]
    #   pos: [1.6, 0., 0.5]
    #   rot:
    #     axis: [1, 0]
    #     angles: [-1.57, 1.57]
    #   params:
    #     dynamic_friction: [0.10, 1.0]
    #     youngs_modulus: [10, 30]
    #     poissons_ratio: [0.1, 0.50]
    #     elasticity_damping: [0.005, 0.5]
    #     damping_scale: [0.1, 1.0]
    # rigid_object2:
    #   path: "source/assets/Plush/usd/duck/usd/duck_rigid.usd"
    #   scale: [1.5, 1.5, 1.5]
    #   pos: [1.4, 0.8, 0.5]
    #   rot:
    #     axis: [0, 2]
    #     angles: [1.57, 1.57]
    #   params:
    #     dynamic_friction: [0.10, 1.0]
    #     youngs_modulus: [10, 30]
    #     poissons_ratio: [0.1, 0.50]
    #     elasticity_damping: [0.005, 0.5]
    #     damping_scale: [0.1, 1.0]
  Camera:
    initial: True
    cameras:
      camera:
        camera_type: "camera"
        height: 480
        width: 640
        data_types: ["rgb", "instance_segmentation_fast"]
        update_period: 0.03
        pos: [0.9, -2.2, 1.4]
        rot:
          axis: [1, 0, 2, 0]
          angles: [-1.57, -1.57, -1.57, -0.55]
      camera1:
        camera_type: "camera"
        height: 480
        width: 640
        data_types: ["rgb", "instance_segmentation_fast"]
        update_period: 0.03
        pos: [0.9, 2.2, 1.4]
        rot:
          axis: [1, 0, 2, 0]
          angles: [-1.57, -1.57, 1.57, 0.55]
      camera2:
        camera_type: "camera"
        height: 480
        width: 640
        data_types: ["rgb", "instance_segmentation_fast"]
        update_period: 0.03
        pos: [3.0, 0, 1.2]
        rot:
          axis: [1, 0, 1]
          angles: [-1.57, -1.57, -0.55]
