# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml#L32
seed: 42

# epoch * n_steps * nenvs: 500Ã—512*8*8
n_timesteps: 163840000000000
policy: 'MlpPolicy'
buffer_size: 1_000_000
batch_size: 2048
policy_kwargs: "dict(net_arch=[256, 128, 64])"
learning_starts: 1000
gradient_steps: 64
tau: 0.002
gamma: 0.98

