RigidObject:
  gripper_0:
    attachment_type: "soft"
    init: True
    path: "source/assets/robot/franka/panda_hand_big.usd"
    scale: [0.01, 0.01, 0.01]
    pos: [0.3, 0.0, .1]
    rot:
      axis: [0]
      angles: [0]
    disable_gravity: True
    motion: True
    relative_pos: False

  # gripper_1:
  #   init: True
  #   path: "source/assets/robot/franka/panda_hand_big.usd"
  #   scale: [0.01, 0.01, 0.01]
  #   pos: [0.3, 0.0, .1]
  #   rot:
  #     axis: [0]
  #     angles: [0]
  #   disable_gravity: True
  #   motion: True
  #   relative_pos: False

  # rigid_cube:
  #   init: True
  #   path: "source/assets/Plush/usd/rabbit/usd/cube_rigid.usd"
  #   scale: [0.1, 0.1, 0.1]
  #   pos: [0.7, 0.0, .0]
  #   rot:
  #     axis: [0]
  #     angles: [0]
  #   disable_gravity: False

  # rigid_cube:
  #   init: True
  #   path: "source/assets/ycb/Axis_Aligned/002_master_chef_can.usd"
  #   scale: [1, 1, 1]
  #   pos: [0.5, 0.0, .0]
  #   rot:
  #     axis: [0]
  #     angles: [-1.57]
