seed: 42

# epoch * n_steps * nenvs: 500Ã—512*8*8
n_timesteps: 163840000000000
policy: 'MultiInputPolicy'
buffer_size: 20_000
batch_size: 512
policy_kwargs: "dict(
  features_extractor_class=ImageStateExtractor,
  features_extractor_kwargs=dict(
  image_key='rgb',
  image_features_dim=256,
 
  state_mlp_size=(64, 64),
  ),
  net_arch=dict(pi=[256, 128, 64], qf=[256, 128, 64]),
  activation_fn=nn.ReLU,
  )"
learning_starts: 2000 #100000
gradient_steps: 16
tau: 0.002
gamma: 0.98

use_residual_schedule: True
residual_schedule_horizon: 10
max_residual_schedule: 500
