DeformableObject:
  deform_object:
    simulation_hexahedral_resolution: 32
    vertex_velocity_damping: 0.0
    random_parmas: False
    sample_node_interval: 50
    gravity_exploration: True

    filter_collision: True
    filter_pair_path:
      - /World/envs/env_.*/gripper
      - /World/envs/env_.*/Robot

    physical_params:
      fix_params:
        youngs_modulus: 500000000
        dynamic_friction: 30.0
        elasticity_damping: 0.0
        density: 0.1

      params_range:
        youngs_modulus: [0, 1.0]
        elasticity_damping: [0, 1.0]
        density: [0, 1.0]
        dynamic_friction: [0, 1.0]
        damping_scale: [0.0, 1.0]
        poissons_ratio: [0, 1.0]

      params_values:
        youngs_modulus: [[0, 6]]
        dynamic_friction: [[0, 1.0]]
        poissons_ratio: [[0, 0.5]]
        elasticity_damping: [[0.0, 0.10]]
        damping_scale: [[0, 1]]
        density: [[0, 1], [1, 10], [10, 100]]

    camera_obs:
      segmentation_name: "instance_segmentation_fast"
      bbox: [-2, -2.0, -0.0, 2.0, 2.0, 1.0]
      max_length: 20480
      whole_pc: True
      seg_pc: True
      whole_rgb: True
      seg_rgb: True
      segmentation_id: 3
      filter_xy_radius: null
      filter_z_threshold: null
      reset_pc_everytime: False
