params:
  arm_type: xarm7
  hand_type: ability
  grasper:
    target_object_name: mustard_bottle
    ee_name: hand_palm
  

  ArticulationObject:

  RigidObject:
    # right_arm_ee:
    #   path: right_hand/raw_right_hand/leap_right/base
    #   spawn: False
    # hand_palm:
    #   path: Robot/leap_right/base
    #   spawn: False

    # tomato_soup_can:
    #   path: "source/assets/ycb/dexgrasp/005_tomato_soup_can/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.0, 0.0, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]
    # master_chef_can:
    #   path: "source/assets/ycb/dexgrasp/002_master_chef_can/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.0, 0.2, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]
    # gelatin_box:
    #   path: "source/assets/ycb/dexgrasp/009_gelatin_box/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.0, 0.4, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]
    # extra_large_clamp:
    #   path: "source/assets/ycb/dexgrasp/052_extra_large_clamp/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.0, -0.2, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # cracker_box:
    #   path: "source/assets/ycb/dexgrasp/003_cracker_box/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.0, -0.4, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # sugar_box:
    #   path: "source/assets/ycb/dexgrasp/004_sugar_box/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.0, -0.6, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # mustard_bottle:
    #   kinematic_enabled: True
    #   path: "source/assets/ycb/dexgrasp/006_mustard_bottle/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [0.40, 0.10, 0.05]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # tuna_fish_can:
    #   path: "source/assets/ycb/dexgrasp/007_tuna_fish_can/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.2, -0.0, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # pudding_box:
    #   path: "source/assets/ycb/dexgrasp/008_pudding_box/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.2, -0.2, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # potted_meat_can:
    #   path: "source/assets/ycb/dexgrasp/010_potted_meat_can/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.2, 0.2, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # banana:
    #   path: "source/assets/ycb/dexgrasp/011_banana/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [0.40, 0.10, 0.05]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # pitcher_base:
    #   path: "source/assets/ycb/dexgrasp/019_pitcher_base/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.2, -0.4, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # bleach_cleanser:
    #   path: "source/assets/ycb/dexgrasp/021_bleach_cleanser/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.2, 0.6, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # bowl:
    #   path: "source/assets/ycb/dexgrasp/024_bowl/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.2, -0.6, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    mug:
      path: "source/assets/ycb/dexgrasp/025_mug/rigid_object.usd"
      scale: [1.0, 1.0, 1.0]
      pos:  [0.60, -0.2, 0.05]
      rot:
        axis: [0]
        angles: [0]

    # power_drill:
    #   path: "source/assets/ycb/dexgrasp/035_power_drill/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.2, 0.8, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # wood_block:
    #   path: "source/assets/ycb/dexgrasp/036_wood_block/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.2, 0.0, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # scissors:
    #   path: "source/assets/ycb/dexgrasp/037_scissors/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [3.2, 0.2, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # large_marker:
    #   path: "source/assets/ycb/dexgrasp/040_large_marker/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.2, -0.2, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # large_clamp:
    #   path: "source/assets/ycb/dexgrasp/051_large_clamp/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.2, -0.4, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # foam_brick:
    #   path: "source/assets/ycb/dexgrasp/061_foam_brick/rigid_object.usd"
    #   scale: [1.0, 1.0, 1.0]
    #   pos: [2.2, 0.4, 0.10]
    #   rot:
    #     axis: [0]
    #     angles: [0]

  AssstObject:

  Camera:
    initial: False
    random_pose: False
    camera_json: null #"source/config/camera/automatic_articulation/kitchen02_cabinet.json"

    max_length: 0
    segmentation_name: "instance_segmentation_fast"
    whole_pc: True
    seg_pc: True
    whole_rgb: True
    seg_rgb: True
    whole_depth: False
    bbox: [-2, -2.0, -0.0, 2.0, 2.0, 1.0] # [-0.20, -0.87, 0.0, 0.60, -0.5, 0.4]
    align_robot_base: True

    pointcloud_setting:
      use_segmentation: True
      segmentation_point_cloud_id: 3
      num_sampled_points: 2048
      segmentation_point_cloud: True
      colorize_point_cloud: True
      num_downsampled_points: 2048

    random_pose_setting:
      origin: [0.5, -0.0, 0.0]
      radius_range: [0.8, 1.2]
      base_rot:
        axis: [1, 0]
        angles: [-1.57, -1.57]
      z_min: 0.7

    cameras:
      camera_01:
        camera_type: "camera"
        height: 480
        width: 640
        data_types:
          ["rgb", "distance_to_image_plane", "instance_segmentation_fast"]
        update_period: 0.03
        eyes: null #[-0.2, 1.0, 0.8]
        target: null #[0.40, -0.0, 0.5]
        translate: [-0.60, 1.40, 0.80]
        euler: [80.0, 0.0, -135]
      camera_02:
        camera_type: "camera"
        height: 480
        width: 640
        data_types:
          ["rgb", "distance_to_image_plane", "instance_segmentation_fast"]
        update_period: 0.03
        eyes: null #[-0.2, 1.0, 0.8]
        target: null #[0.40, -0.0, 0.5]
        translate: [-0.10, -0.8, 1.3]
        euler: [45.0, 0.0, -15]

      camera_03:
        camera_type: "camera"
        height: 480
        width: 640
        data_types:
          ["rgb", "distance_to_image_plane", "instance_segmentation_fast"]
        update_period: 0.03
        eyes: null #[-0.2, 1.0, 0.8]
        target: null #[0.40, -0.0, 0.5]
        translate: [-0.60, 0.20, 1.7]
        euler: [40.0, 0.0, -100]
