defaults:
  - _self_
  - task: hand_state

name: train_diffusion_unet_state
_target_: scripts.workflows.hand_manipulation.utils.diffusion.train_cfm_lowdim_policy.TrainCFMUnetLowdimWorkspace


task_name: hand_state
exp_name: "default"

horizon: 16
n_obs_steps: 2
n_action_steps: 8
n_latency_steps: 0
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_local_cond: False
obs_as_global_cond: True
pred_action_steps_only: False




obs_dim: 47
action_dim: 22
policy:
  _target_: scripts.workflows.hand_manipulation.utils.diffusion.policy.cfm_unet_lowdim_policy.CFMnetLowdimPolicy

  model:
    _target_: diffusion_policy.model.diffusion.conditional_unet1d.ConditionalUnet1D
    input_dim: "${eval:  ${action_dim} if ${obs_as_local_cond} or ${obs_as_global_cond} else ${obs_dim} +  ${action_dim}}"
    local_cond_dim: "${eval: ${obs_dim} if ${obs_as_local_cond} else None}"
    global_cond_dim: "${eval: ${obs_dim}*${n_obs_steps} if ${obs_as_global_cond} else None}"
    diffusion_step_embed_dim: 256
    down_dims: [256, 512]
    kernel_size: 5
    n_groups: 8
    cond_predict_scale: True
  inference_function:
    _target_: scripts.workflows.hand_manipulation.utils.diffusion.utils.inference_utils.RK2

  noise_scheduler:
    _target_: torchcfm.ConditionalFlowMatcher
    sigma: 0.0

  horizon: ${horizon}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 2
  obs_as_local_cond: ${obs_as_local_cond}
  obs_as_global_cond: ${obs_as_global_cond}
  pred_action_steps_only: ${pred_action_steps_only}
  oa_step_convention: True

  # scheduler.step params
  # predict_epsilon: True
    

dataset:
  _target_: scripts.workflows.hand_manipulation.utils.diffusion.dataset.pickandplace_low_dim_dataset.PickandPlaceLowdimDataset
  data_path: None
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_obs_steps}-1'}
  obs_key:
    [
      right_ee_pose, right_hand_joint_pos, right_manipulated_object_pose #right_hand_place_object_pose
    ]
  image_key: []
  noise_key: [right_hand_joint_pos] #right_hand_joint_pos
  action_key: "action"
  seed: ${training.seed}
  noise_scale: 0.05
  val_ratio: 0.05
  add_time_stamp: False


  num_demo : 500
 
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 512
  num_workers: 1
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 512
  num_workers: 32
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: False
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 1000
  gradient_accumulate_every: 1
  use_ema: True
  # training loop control
  # in epochs
  rollout_every: 100
  checkpoint_every: 100
  val_every: 100
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: diffusion_policy_debug
  resume: False
  mode: online
  name: manipulation_state_cfm_unet
  tags: ["diffusion", "unet", "state"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_loss
    mode: max
    k: 5
    format_str: "epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt"
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: logs/
  wandb_name_base: manipulation_cfm_unet

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: logs/
  sweep:
    dir: logs/
    subdir: manipulation_state_cfm_unet
