params:
  DeformableObject:
    deform_object:
      env_setting:
        camera_obs:
          segmentation_id: 3
        filter_pair_path:
          - /World/envs/env_.*/gripper_0
          - /World/envs/env_.*/broom01
          - /World/envs/env_.*/broom01_rigid_attachment
        floating_gripper:
          gripper_actions: -1
          gripper_offset: 0.12
          gripper_offset_xyz:
            - 0.5
            - 0.0
            - 0.09
          random_orientation_range:
            - 0.0
            - 0.0
          random_position_dir:
            - - -0.02
              - 0.0
              - 0.0
            - - 0.0
              - 0.02
              - 0.0
            - - 0.0
              - 0.0
              - 0.02
          static_frames: 4
        path: source/assets/attachment/broom01/broom01_deformable_base.usd
        pos:
          - 1.0
          - -0.0
          - 0.0
        pose_range: null
        rot:
          angles: [1.57, 1.57]
          axis: [1, 2]
        scale:
          - 4
          - 4
          - 4
        velocity_range: null
        attach_robot:
          init: True
          attach_object_path: "/World/envs/env_.*/broom01_rigid_attachment"
          attach_offset: [0, 0, -0.0]
          attact_yet: False
          DeformableVertexOverlapOffset: 0.04

  RigidObject:
    rigid_attachment:
      init: True
      path: "source/assets/attachment/broom01/broom01_rigid_handle.usd"
