kinematics_path: source/config/task/hand_env/teleoperation/bunny/kinematics_config/bimanual_panda_gripper.yml
xrcfg_xyz: [-0.0, 0.0, -0.6]
xrcfg_quat: [0.707, 0, 0, -0.707]
pose_factor: 1.0
low_pass_smoothing_wrist: 0.4
use_motion_filter: True
retarget_type: vectorada
init_ee_pose: [0.40, -0.000, 0.200, 0.0, 9.2460e-01, -3.8094e-01, 0.0]
