params:
  Task:
    Failure:
      grasper:
        xyz_grasp_offset: [[0.03,0.06], [0.04,0.07],[0.04,0.15]]
        slip_frame_offset: [20, 60]
        rpy_grasp_offset: [[0.2,0.8], [0.2,0.8],[0.4,1.0]]
        open_speed_offset: [0.03,0.06]







































































































































































































































































































































































































































































































































































