params:
  Task:
    Failure:
      grasper:
        xyz_grasp_offset: [[0.03,0.06], [0.04,0.07],[0.04,0.15]]
        slip_frame_offset: [8, 4]








































































































































































































































































































































































































































































































































































