params:
  Task:
    Failure:
      grasper:
        xyz_grasp_offset: [[0.02,0.06], [0.05,0.12],[0.04,0.10]]
        xyz_grasp_sign_offset: [[-1], [-1],[-1,1]]
        slip_frame_offset: [20, 60]
        rpy_grasp_offset: [[0.3,0.6], [0.2,0.8],[0.1,0.5]]
        open_speed_offset: [0.03,0.06]







































































































































































































































































































































































































































































































































































