params:
  Task:
    Failure:
      grasper:
        xyz_grasp_offset: [[0.02,0.04], [0.04,0.06],[0.03,0.05]]
        rpy_grasp_offset: [[0.02,0.04], [0.04,0.06],[0.7,1.5]]
        xyz_placement_offset:  [[0.03,0.10], [0.03,0.10],[0.03,0.05]]
        slip_frame_offset: [70, 90]








































































































































































































































































































































































































































































































































































