left:
  retargeting:
    type: position

    urdf_path: source/assets/robot/leap_hand_v2/archive/leap_hand/leap_hand_left_glb.urdf

    target_joint_names: null
    target_link_names:
      [
        "thumb_tip_head",
        "index_tip_head",
        "middle_tip_head",
        "ring_tip_head",
        "thumb_dip",
        "dip",
        "dip_2",
        "dip_3",
      ]

    target_link_human_indices: [4, 8, 12, 20, 2, 6, 10, 18]
    # add_dummy_free_joint: True

    # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
    # 1 means no filter while 0 means not moving
    low_pass_alpha: 1

  control:
    type: pinocchio

    robot_name: leap_left

    # Config path with more details about the robot and its kinematics
    robot_config_path: leap_left.yml

    # Low pass filter for arm
    # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
    low_pass_alpha: 0.05

    # Set True if you do not want to control the orientation of hand
    disable_orientation_control: False

    # Set to a smaller value for first trial before you are familiar with the system
    # In most cases, it should be smaller than 1
    motion_scaling_factor: 1.0

right:
  retargeting:
    type: position
    urdf_path: source/assets/robot/leap_hand_v2/archive/leap_hand/leap_hand_right_glb.urdf

    # urdf_path: source/assets/dex_urdf/robots/hands/leap_hand/leap_hand_right_glb.urdf

    target_joint_names: null
    target_link_names: [
        # "base",
        "thumb_tip_head",
        "index_tip_head",
        "middle_tip_head",
        "ring_tip_head",
        "thumb_dip",
        "dip",
        "dip_2",
        # "dip_3",
      ]

    target_link_human_indices:  [ 4, 8, 16, 20, 2, 6, 14]

    # target_link_names:
    #   [

    #     "thumb_tip_head",
    #     "index_tip_head",
    #     "middle_tip_head",
    #     "ring_tip_head",
    #   ]

    # target_link_human_indices: [0, 4, 8, 12, 16]
    add_dummy_free_joint: False

    # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
    # 1 means no filter while 0 means not moving
    low_pass_alpha: 1

  control:
    type: pinocchio

    robot_name: leap_right

    robot_config_path: leap_right.yml

    low_pass_alpha: 0.05

    disable_orientation_control: False

    motion_scaling_factor: 1.0
