left:
  retargeting:
    type: dexpilot

    urdf_path: source/assets/robot/leap_hand_v2/archive/leap_hand/free_leap_hand_left_glb.urdf

    wrist_link_name: "base"
    target_origin_link_names: ["base", "base", "base", "base"]
    target_task_link_names:
      ["thumb_tip_head", "index_tip_head", "middle_tip_head", "ring_tip_head"]
    finger_tip_link_names:
      ["thumb_tip_head", "index_tip_head", "middle_tip_head", "ring_tip_head"]
    scaling_factor: 1.6
    # target_link_human_indices: [[0, 0, 0, 0], [4, 8, 12, 16]]
    # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
    low_pass_alpha: 0.2

right:
  retargeting:
    type: dexpilot
    urdf_path: source/assets/robot/leap_hand_v2/archive/leap_hand/free_leap_hand_right_glb.urdf

    # urdf_path: source/assets/dex_urdf/robots/hands/leap_hand/leap_hand_right_glb.urdf

    # Target refers to the retargeting target, which is the robot hand
    wrist_link_name: "base"
    target_origin_link_names: ["base", "base", "base", "base","base", "base", "base", "base"]
    target_task_link_names:
      [
        "thumb_tip_head",
        "index_tip_head",
        "middle_tip_head",
        "ring_tip_head",
        "thumb_dip",
        "dip",
        "dip_2",
        "dip_3",
      ]
    finger_tip_link_names:
      [
        "thumb_tip_head",
        "index_tip_head",
        "middle_tip_head",
        "ring_tip_head",
        # "thumb_dip",
        # "dip",
        # "dip_2",
        # "dip_3",
      ]
    # target_link_human_indices:
    #   [[0, 0, 0, 0, 0, 0, 0, 0], [4, 8, 12, 16, 2, 6, 10, 14]]
    scaling_factor: 2.4

    # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
    low_pass_alpha: 0.2
