left:
  retargeting:
    type: vector #dexpilot

    urdf_path: source/assets/robot/leap_hand_v2/archive/leap_hand/leap_hand_left_glb.urdf

    wrist_link_name: "base"
    target_origin_link_names: [ "base", "base", "base", "base" ]
    target_task_link_names: [ "thumb_tip_head", "index_tip_head", "middle_tip_head", "ring_tip_head" ]
    finger_tip_link_names:
      ["thumb_tip_head", "index_tip_head", "middle_tip_head", "ring_tip_head"]
    scaling_factor: 1.6
    target_link_human_indices: [ [ 0, 0, 0, 0 ], [ 4, 8, 12, 16 ] ]
    # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
    low_pass_alpha: 0.2

right:
  retargeting:
    type: vector
    urdf_path: source/assets/robot/leap_hand_v2/archive/leap_hand/leap_hand_right_glb.urdf

    # urdf_path: source/assets/dex_urdf/robots/hands/leap_hand/leap_hand_right_glb.urdf

    # Target refers to the retargeting target, which is the robot hand
    wrist_link_name: "base"
    target_origin_link_names: [ "base", "base", "base", "base" ]
    target_task_link_names: [ "thumb_tip_head", "index_tip_head", "middle_tip_head", "ring_tip_head" ]
    finger_tip_link_names:
      ["thumb_tip_head", "index_tip_head", "middle_tip_head", "ring_tip_head"]
    target_link_human_indices: [ [ 0, 0, 0, 0 ], [ 4, 8, 12, 16 ] ]
    scaling_factor:  1.6

    # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
    low_pass_alpha: 0.2
