params:
  arm_type: ur5e
  hand_type: ability
  arm_mesh_dir: "source/assets/robot/ur5e/raw_mesh"
  hand_mesh_dir: "source/assets/robot/ability_hand/raw_mesh"
  num_hand_joints: 10
  num_arm_joints: 6
  left_robot_pose: [0.0, 0.3, 0.0, 1.0, 0.0, 0.0,0.0]
  right_robot_pose: [0.0, -0.3, 0.0, 1.0, 0.0, 0.0,0.0]
  viser_camera_pose: [1.0, 0.0, 0.5, 0.0, 0.0, 0.0]

  spawn_robot:
    init: True
    colorize_pc: True
    spawn_arm: True

    right_hand:
      main_path: "right_hand/right_ability/ability_hand"
      spawn_list:
        [
          "right_index_1",
          "right_palm_lower",
          "right_index_2",
          "right_middle_1",
          "right_middle_2",
          "right_pinky_1",
          "right_pinky_2",
          "right_ring_1",
          "right_ring_2",
          "right_thumb_1",
          "right_thumb_2",
        ]
    left_hand:
      main_path: "left_hand/left_ability/ability_hand"
      spawn_list:
        [
          "left_index_1",
          "left_palm_lower",
          "left_index_2",
          "left_middle_1",
          "left_middle_2",
          "left_pinky_1",
          "left_pinky_2",
          "left_ring_1",
          "left_ring_2",
          "left_thumb_1",
          "left_thumb_2",
        ]

    right_arm:
      main_path: "right_hand"
      spawn_list: [
          # "right_base_link_inertia",
          "right_shoulder_link",
          "right_upper_arm_link",
          "right_forearm_link",
          "right_wrist_1_link",
          "right_wrist_2_link",
          "right_wrist_3_link",
        ]
    left_arm:
      main_path: "left_hand"
      spawn_list: [
          # "left_base_link_inertia",
          "left_shoulder_link",
          "left_upper_arm_link",
          "left_forearm_link",
          "left_wrist_1_link",
          "left_wrist_2_link",
          "left_wrist_3_link",
        ]

    num_downsample_points: 512
  grasper:
    target_object_name: mustard_bottle
    ee_name: hand_palm
    init_robot_qos:
      [
       -4.7864e-01, -1.5635e+00,  2.3770e+00, -8.1342e-01,  1.0922e+00,
          3.5476e-07
      ]
    joint_names:
      [

       'shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint', 'index_q1', 'middle_q1', 'ring_q1', 'pinky_q1', 'thumb_q1', 'index_q2', 'middle_q2', 'ring_q2', 'pinky_q2', 'thumb_q2'
      ]
  spawn_rigid_objects:
    init: True
    object_mesh_dir: "source/assets/ycb/dexgrasp/raw"
    spawn_list: ["banana"]

  ArticulationObject:

  RigidObject:
    banana:
      path: "source/assets/ycb/dexgrasp/raw/banana/rigid_object.usd"
      scale: [1.0, 1.0, 1.0]
      pos: [0.50, -0.0, 0.05]
      rot:
        axis: [0]
        angles: [0]

  Camera:
    initial: False
    random_pose: False
    camera_json: null #"source/config/camera/automatic_articulation/kitchen02_cabinet.json"

    max_length: 0
    segmentation_name: "instance_segmentation_fast"
    whole_pc: True
    seg_pc: True
    whole_rgb: True
    seg_rgb: True
    whole_depth: False
    bbox: [-2, -2.0, -0.0, 2.0, 2.0, 1.0] # [-0.20, -0.87, 0.0, 0.60, -0.5, 0.4]
    align_robot_base: True

    pointcloud_setting:
      use_segmentation: True
      segmentation_point_cloud_id: 3
      num_sampled_points: 2048
      segmentation_point_cloud: True
      colorize_point_cloud: True
      num_downsampled_points: 2048

    random_pose_setting:
      origin: [0.5, -0.0, 0.0]
      radius_range: [0.8, 1.2]
      base_rot:
        axis: [1, 0]
        angles: [-1.57, -1.57]
      z_min: 0.7

    cameras:
      camera_01:
        camera_type: "camera"
        height: 480
        width: 640
        data_types:
          ["rgb", "distance_to_image_plane", "instance_segmentation_fast"]
        update_period: 0.03
        eyes: null #[-0.2, 1.0, 0.8]
        target: null #[0.40, -0.0, 0.5]
        translate: [-0.60, 1.40, 0.80]
        euler: [80.0, 0.0, -135]
      camera_02:
        camera_type: "camera"
        height: 480
        width: 640
        data_types:
          ["rgb", "distance_to_image_plane", "instance_segmentation_fast"]
        update_period: 0.03
        eyes: null #[-0.2, 1.0, 0.8]
        target: null #[0.40, -0.0, 0.5]
        translate: [-0.10, -0.8, 1.3]
        euler: [45.0, 0.0, -15]

      camera_03:
        camera_type: "camera"
        height: 480
        width: 640
        data_types:
          ["rgb", "distance_to_image_plane", "instance_segmentation_fast"]
        update_period: 0.03
        eyes: null #[-0.2, 1.0, 0.8]
        target: null #[0.40, -0.0, 0.5]
        translate: [-0.60, 0.20, 1.7]
        euler: [40.0, 0.0, -100]
