params:
  ArticulationObject:
    kitchen:
      name: kitche
      path: "tools/auto_articulation/asset/acdc_kitchen/acdc/main.usdc"
      scale: [1.0, 1.0, 1.0]
      pos: [0, 0, 0]
      rot:
        axis: [0, 1, 2]
        angles: [0, 0, 0]
      disable_gravity: True
      enabled_self_collisions: False
      joints:
        PrismaticJoint: 0.0

      action_horiozon:
        approach: 15
        close: 5
        open: 60
        open_speed: 0.005
        lift: 20
        lift_speed: 0.015
        close_speed: 0.015
        close_cabinet: 30
        close_descend: 5
      target_drawer: mesh_0020
      target_object: mug
      robot_random_range:
        mesh_0020:
          pose_range:
            x: [0.0, 0.0]
            y: [-0.0, 0.0]
            z: [0.20, 0.20]
            yaw: [-0.0, 0.0]
          joint_random_range:
            position_range: [-0.01, 0.01]
          offset: [-0.0, -0.0, -0.00]
          delta_euler: [[2, 1], [0.5, -0.5]]
          joint_name: PrismaticJoint
  RigidObject:
    mug:
      path: "source/assets/ycb/Axis_Aligned/025_mug.usd"
      scale: [1, 1, 1]
      pos: [-0.50, -0.0, 0.45]
      rot:
        axis: [0]
        angles: [-1.57]
      pose_range:
        x: [0.0, 0.10]
        y: [-0.25, 0.05]
        z: [0.0, 0.0]
        yaw: [-1.0, 1.0]

  Camera:
    initial: False
    random_pose: False

    max_length: 0
    segmentation_name: "instance_segmentation_fast"
    whole_pc: True
    seg_pc: True
    whole_rgb: True
    seg_rgb: True
    whole_depth: False
    bbox: [-2, -2.0, -0.0, 2.0, 2.0, 1.0] # [-0.20, -0.87, 0.0, 0.60, -0.5, 0.4]
    align_robot_base: True

    pointcloud_setting:
      use_segmentation: True
      segmentation_point_cloud_id: 3
      num_sampled_points: 2048
      segmentation_point_cloud: True
      colorize_point_cloud: True
      num_downsampled_points: 2048

    random_pose_setting:
      origin: [0.5, -0.0, 0.0]
      radius_range: [0.8, 1.2]
      base_rot:
        axis: [1, 0]
        angles: [-1.57, -1.57]
      z_min: 0.7

    cameras:
      # camera_00:
      #   camera_type: "tiled_camera"
      #   height: 480
      #   width: 640
      #   data_types:
      #     ["rgb", "distance_to_image_plane", "instance_segmentation_fast"]
      #   update_period: 0.03
      #   eyes: [0.2, -1.5, 1.0] #[1.60, -0.8, 1.2]
      #   target: [0.40, -0.4, 0.60]
      # camera_02:
      #   camera_type: "tiled_camera"
      #   height: 480
      #   width: 640
      #   data_types:
      #     ["rgb", "distance_to_image_plane", "instance_segmentation_fast"]
      #   update_period: 0.03
      #   eyes: [0.0, 0.7, 1.0]
      #   target: [0.40, -0.0, 0.60]

      camera_03:
        camera_type: "tiled_camera"
        height: 480
        width: 640
        data_types:
          ["rgb", "distance_to_image_plane", "instance_segmentation_fast"]
        update_period: 0.03
        eyes: [0.0, -1.5, 0.8]
        target: [0.55, -0.4, 0.40]

      camera_01:
        camera_type: "tiled_camera"
        height: 480
        width: 640
        data_types:
          ["rgb", "distance_to_image_plane", "instance_segmentation_fast"]
        update_period: 0.03
        eyes: [-0.5, -0.8, 0.5]
        target: [0.55, -0.4, 0.20]
