params:
  ArticulationObject:
    kitchen:
      name: kitchen
      path: "tools/auto_articulation/asset/uw_kitchen/kitchen.usda"
      scale: [3.5, 3.74, 3.87]
      pos: [0.27, 0.70, 0.78]
      rot:
        axis: [0, 1, 2]
        angles: [-0.145, -0.078, -2.11]
      disable_gravity: True
      enabled_self_collisions: False
      joints:
        # drawer_revolute_joint_2: 0.0
        # drawer_revolute_joint_3: 0.0
        # drawer_revolute_joint_4: 0.0
        # drawer_revolute_joint_5: 0.0
        # drawer_revolute_joint_6: 0.0
        # drawer_revolute_joint_7: -0.0
        # drawer_revolute_joint_8: 0.0
        # drawer_revolute_joint_9: -0.0
        # drawer_revolute_joint_10: -0.0
        # drawer_revolute_joint_11: -0.0
        # drawer_revolute_joint_12: 0.0
        # drawer_revolute_joint_13: -0.0

        #revolute_joint
        drawer_prismatic_joint_0: 0.0
        drawer_prismatic_joint_1: 0.0
      action_horiozon:
        approach: 15
        close: 8
        open: 20
        open_speed: 0.015
        lift: 15
        lift_speed: 0.02
        close_speed: 0.03
        close_cabinet: 20
        close_descend: 5
      target_drawer: drawer_00_handle
      target_object: mug
      robot_random_range:
        drawer_00_handle:
          pose_range:
            x: [-0.075, 0.075] #[-0.075, 0.075] #[-0.10, 0.10]
            y: [-0.10, 0.02] #[-0.10, 0.02]
            z: [-0.02, 0.13] #[-0.02, 0.13]
            yaw: [-0.10, 0.10]

          joint_random_range:
            position_range: [-0.0, 0.0]
          offset: [0.01, -0.0, 0.0]
          delta_euler: [[2, 1], [0.5, -0.02]]
          joint_name: drawer_prismatic_joint_0
        drawer_01_handle:
          pose_range:
            x: [-0.05, 0.05]
            y: [-0.05, 0.05]
            z: [-0.04, 0.04]
            yaw: [-0.1, 0.1]
          joint_random_range:
            position_range: [-0.03, 0.03]
          offset: [0.02, -0.0, 0.02]
          delta_euler: [[2, 1], [0.5, -0.5]]
          joint_name: drawer_prismatic_joint_1
      random_camera: True

  RigidObject:
    mug:
      path: "source/assets/ycb/Axis_Aligned/025_mug.usd"
      scale: [1, 1, 1]
      pos: [0.50, -0.40, 0.47]
      rot:
        axis: [0]
        angles: [-1.57]
      pose_range:
        x: [0.0, 0.0]
        y: [0.00, 0.30]
        z: [0.0, 0.0]
        yaw: [-2.0, 2.0]
    # mug:
    #   path: "source/assets/ycb/Axis_Aligned/010_potted_meat_can.usd"
    #   scale: [1, 1, 1]
    #   pos: [0.49, -0.40, 0.45]
    #   rot:
    #     axis: [0]
    #     angles: [-1.57]
    #   pose_range:
    #     x: [0.0, 0.05]
    #     y: [0.00, 0.30]
    #     z: [0.0, 0.0]
    #     yaw: [-2.0, 2.0]

  Camera:
    initial: False
    random_pose: False
    camera_json: "source/config/camera/automatic_articulation/kitchen02_cabinet.json"

    max_length: 0
    segmentation_name: "instance_segmentation_fast"
    whole_pc: True
    seg_pc: True
    whole_rgb: True
    seg_rgb: True
    whole_depth: False
    bbox: [-2, -2.0, -0.0, 2.0, 2.0, 1.0] # [-0.20, -0.87, 0.0, 0.60, -0.5, 0.4]
    align_robot_base: True

    pointcloud_setting:
      use_segmentation: True
      segmentation_point_cloud_id: 3
      num_sampled_points: 2048
      segmentation_point_cloud: True
      colorize_point_cloud: True
      num_downsampled_points: 2048

    random_pose_setting:
      origin: [0.5, -0.0, 0.0]
      radius_range: [0.8, 1.2]
      base_rot:
        axis: [1, 0]
        angles: [-1.57, -1.57]
      z_min: 0.7

    cameras:
      # camera_00:
      #   camera_type: "tiled_camera"
      #   height: 480
      #   width: 640
      #   data_types:
      #     ["rgb", "distance_to_image_plane", "instance_segmentation_fast"]
      #   update_period: 0.03
      #   eyes: [-0.20, -1.0, 0.7] #[0.60, -0.8, 1.2]
      #   target: [0.20, -0.0, 0.5] #[0.55, -0.51924, 0.22789]

      camera_01:
        camera_type: "camera"
        height: 480
        width: 640
        data_types:
          ["rgb", "distance_to_image_plane", "instance_segmentation_fast"]
        update_period: 0.03
        eyes: null #[-0.2, 1.0, 0.8]
        target: null #[0.40, -0.0, 0.5]
        translate: [0.18727499786966892, 0.4852828855270812, 0.66530460832038]
        euler: [-135, 6.9, 134]
