params:
  RigidObject:
    mug:
      path: source/assets/ycb/dexgrasp/recenter_objects/mug/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.044075001031160355
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    large_clamp:
      path: source/assets/ycb/dexgrasp/recenter_objects/large_clamp/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.03187499940395355
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    extra_large_clamp:
      path: source/assets/ycb/dexgrasp/recenter_objects/extra_large_clamp/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.04615600034594536
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    large_marker:
      path: source/assets/ycb/dexgrasp/recenter_objects/large_marker/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.0038419999182224274
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    gelatin_box:
      path: source/assets/ycb/dexgrasp/recenter_objects/gelatin_box/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.04374400153756142
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    bowl:
      path: source/assets/ycb/dexgrasp/recenter_objects/bowl/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.02135399915277958
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    foam_brick:
      path: source/assets/ycb/dexgrasp/recenter_objects/foam_brick/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.017416000366210938
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    bleach_cleanser:
      path: source/assets/ycb/dexgrasp/recenter_objects/bleach_cleanser/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.03085399977862835
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    power_drill:
      path: source/assets/ycb/dexgrasp/recenter_objects/power_drill/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.11112499982118607
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    banana:
      path: source/assets/ycb/dexgrasp/recenter_objects/banana/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.03154199942946434
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    sugar_box:
      path: source/assets/ycb/dexgrasp/recenter_objects/sugar_box/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.04675700142979622
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    pudding_box:
      path: source/assets/ycb/dexgrasp/recenter_objects/pudding_box/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.039597999304533005
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    mustard_bottle:
      path: source/assets/ycb/dexgrasp/recenter_objects/mustard_bottle/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.0336729995906353
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    potted_meat_can:
      path: source/assets/ycb/dexgrasp/recenter_objects/potted_meat_can/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.037411998957395554
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    scissors:
      path: source/assets/ycb/dexgrasp/recenter_objects/scissors/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.018880000337958336
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    master_chef_can:
      path: source/assets/ycb/dexgrasp/recenter_objects/master_chef_can/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.043345000594854355
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    tomato_soup_can:
      path: source/assets/ycb/dexgrasp/recenter_objects/tomato_soup_can/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.027963999658823013
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
    tuna_fish_can:
      path: source/assets/ycb/dexgrasp/recenter_objects/tuna_fish_can/recenter_rigid_object.usd
      kinematic_enabled: false
      scale:
        - 1.0
        - 1.0
        - 1.0
      pos:
        - 0.5
        - 0.0
        - 0.018719999119639397
      rot:
        axis:
          - 0
        angles:
          - 1.57
      pose_range:
        x:
          - -0.2
          - 0.2
        y:
          - -0.2
          - 0.2
        z:
          - 0.0
          - 0.0
        roll:
          - 0.0
          - 0.0
        yaw:
          - -3.14
          - 3.14
