params:
  DeformableObject:
    deform_object:
      env_setting:
        attach_robot:
          DeformableVertexOverlapOffset: -0.0
        camera_obs:
          filter_xy_radius: 0.2
          filter_z_threshold: 0.05
          segmentation_id: 3
        filter_pair_path:
          - /World/envs/env_.*/gripper
          - /World/envs/env_.*/deform_object/duck/Mesh/Mesh
        floating_gripper:
          gripper_offset:
            - 0.0
            - 0.0
            - 0.06
          gripper_offset_xyz:
            - 0.5
            - 0.0
            - 0.0
        path: source/assets/Plush/usd/duck/usd/duck_deform.usd
        pos:
          - 0.6
          - -0.0
          - 0.01
        pose_range: null
        rot:
          angles:
            - 0.707
          axis:
            - 2
        scale:
          - 1.0
          - 1.0
          - 1.0
        velocity_range: null

        physical_params:
          params_values:
            elasticity_damping: [[0.0, 0.1]]
