params:
  DeformableObject:
    deform_object:
      env_setting:
        attach_robot:
          DeformableVertexOverlapOffset: -0.0
        camera_obs:
          filter_xy_radius: 0.2
          filter_z_threshold: 0.03
          segmentation_id: 3
        filter_pair_path:
          - /World/envs/env_.*/gripper
          - /World/envs/env_.*/deform_object/hat/Mesh/Mesh

        floating_gripper:
          gripper_offset: 0.03
          gripper_offset_xyz:
            - 0.6
            - 0.0
            - 0.09
        path: source/assets/Plush/usd/hat/hat_deform.usd
        pos:
          - 0.6
          - -0.0
          - 0.01
        pose_range: null
        rot:
          angles:
            - 0
          axis:
            - 0
        scale:
          - 1.0
          - 1.0
          - 1.0
        velocity_range: null
