params:
  DeformableObject:
    deform_object:
      env_setting:
        camera_obs:
          segmentation_id: 3
        filter_pair_path:
          - /World/envs/env_.*/gripper
          - /World/envs/env_.*/deform_object/sweep/Mesh/Mesh
        floating_gripper:
          gripper_actions: -1
          gripper_offset: 0.12
          gripper_offset_xyz:
            - 0.5
            - 0.0
            - 0.09
          random_orientation_range:
            - 0.0
            - 0.0
          random_position_dir:
            - - -0.02
              - 0.0
              - 0.0
            - - 0.0
              - 0.02
              - 0.0
            - - 0.0
              - 0.0
              - 0.02
          static_frames: 4
        path: source/assets/Plush/usd/sweep/sweep_deform.usd
        pos:
          - 0.5
          - -0.0
          - 0.01
        pose_range: null
        rot:
          angles:
            - 0
          axis:
            - 0
        scale:
          - 1.5
          - 1.5
          - 1.5
        velocity_range: null
